publisher:
- name: Paizo, Inc.
  website: https://paizo.com
source:
- abbr: CRB
  descr: Volume containing the rules core rules for players and Game Masters
  full_name: Pathfinder Core Rulebook (Second Edition)
  is_first_party: true
  isbn: 978-1-64078-168-9
  ogl_copyright_block: 'Open Game License v.1.0a (c) 2000, Wizards of the Coast, Inc.;
    System Reference Document (c) 2000, Wizards of the Coast, Inc.; Authors: Jonathan
    Tweet, Monte Cook, and Skip Williams, based on material by E. Gary Gygax and Dave
    Arneson. Pathfinder Core Rulebook (Second Edition) (c) 2019, Paizo, Inc.; Designers:
    Logan Bonner, Jason Bulmahn, Stephen Radney-MacFarland, and Mark Seifter.'
  publisher_name: Paizo, Inc.
  pzocode: PZO2101
  release_date: 2019-08-01
  short_name: Core Rulebook
- abbr: ERR-CRB-1.0
  descr: Errata to the Core Rulebook
  full_name: Pathfinder Core Rulebook (Second Edition), First Printing, Update 1.0
  is_first_party: true
  isbn: null
  ogl_copyright_block: 'Open Game License v.1.0a (c) 2000, Wizards of the Coast, Inc.;
    System Reference Document (c) 2000, Wizards of the Coast, Inc.; Authors: Jonathan
    Tweet, Monte Cook, and Skip Williams, based on material by E. Gary Gygax and Dave
    Arneson. Pathfinder Core Rulebook (Second Edition) (c) 2019, Paizo, Inc.; Designers:
    Logan Bonner, Jason Bulmahn, Stephen Radney-MacFarland, and Mark Seifter. Pathfinder
    Core Rulebook (Second Edition), First Printing, Update 1.0 (c) 2019, Paizo, Inc.;
    Authors: Logan Bonner, Lyz Liddell, and Mark Seifter.'
  publisher_name: Paizo, Inc.
  pzocode: PZO2101+Errata+1.0
  release_date: 2019-10-30
  short_name: Core Rulebook Errata 1.0
- abbr: BST1
  descr: Volume containing monster stat blocks and rules primarily for Game Masters
  full_name: Pathfinder Bestiary (Second Edition)
  is_first_party: true
  isbn: 978-1-64078-170-2
  ogl_copyright_block: 'Open Game License v.1.0a (c) 2000, Wizards of the Coast, Inc.;
    System Reference Document (c) 2000, Wizards of the Coast, Inc.; Authors: Jonathan
    Tweet, Monte Cook, and Skip Williams, based on material by E. Gary Gygax and Dave
    Arneson. Daemon, Guardian from the Tome of Horrors Complete © 2011, Necromancer
    Games, Inc., published and distributed by Frog God Games; Author: Scott Greene,
    based on original material by Ian McDowall. Dark Creeper from the Tome of Horrors
    Complete © 2011, Necromancer Games, Inc., published and distributed by Frog God
    Games; Author: Scott Greene, based on original material by Rik Shepard. Dark Stalker
    from the Tome of Horrors Complete © 2011, Necromancer Games, Inc., published and
    distributed by Frog God Games; Author: Scott Greene, based on original material
    by Simon Muth. Dragon, Faerie from the Tome of Horrors Complete © 2011, Necromancer
    Games, Inc., published and distributed by Frog God Games; Author: Scott Greene,
    based on original material by Brian Jaeger and Gary Gygax. Genie, Marid from the
    Tome of Horrors Complete © 2011, Necromancer Games, Inc., published and distributed
    by Frog God Games; Author: Scott Greene, based on original material by Gary Gygax.
    Mite from the Tome of Horrors Complete © 2011, Necromancer Games, Inc., published
    and distributed by Frog God Games; Author: Scott Greene, based on original material
    by Ian Livingstone and Mark Barnes. Pathfinder Bestiary (Second Edition) © 2019,
    Paizo Inc.; Authors: Alexander Augunas, Logan Bonner, Jason Bulmahn, John Compton,
    Paris Crenshaw, Adam Daigle, Eleanor Ferron, Leo Glass, Thurston Hillman, James
    Jacobs, Jason Keeley, Lyz Liddell, Ron Lundeen, Robert G. McCreary, Tim Nightengale,
    Stephen Radney-MacFarland, Alex Riggs, David N. Ross, Michael Sayre, Mark Seifter,
    Chris S. Sims, Jeffrey Swank, Jason Tondro, Tonya Woldridge, and Linda Zayas-Palmer.'
  publisher_name: Paizo, Inc.
  pzocode: PZO2102
  release_date: 2019-08-01
  short_name: Bestiary
- abbr: TFoP
  descr: TODO
  full_name: 'Pathfinder Adventure: The Fall of Plaguestone'
  is_first_party: true
  isbn: 978-1-64078-174-0
  ogl_copyright_block: 'Open Game License v.1.0a (c) 2000, Wizards of the Coast, Inc.;
    System Reference Document (c) 2000, Wizards of the Coast, Inc.; Authors: Jonathan
    Tweet, Monte Cook, and Skip Williams, based on material by E. Gary Gygax and Dave
    Arneson. Pathfinder Adventure: The Fall of Plaguestone © 2019, Paizo Inc.; Author:
    Jason Bulmahn.'
  publisher_name: Paizo, Inc.
  pzocode: PZO9555
  release_date: 2019-08-01
  short_name: The Fall of Plaguestone
- abbr: AoAPG
  descr: Player's Guide for the Age of Ashes Adventure Path
  full_name: Age of Ashes Player's Guide
  is_first_party: true
  isbn: null
  ogl_copyright_block: 'Open Game License v.1.0a (c) 2000, Wizards of the Coast, Inc.;
    System Reference Document (c) 2000, Wizards of the Coast, Inc.; Authors: Jonathan
    Tweet, Monte Cook, and Skip Williams, based on material by E. Gary Gygax and Dave
    Arneson. Age of Ashes Player''''s Guide © 2019, Paizo Inc.; Authors: James Jacobs
    with Amanda Hamon.'
  publisher_name: Paizo, Inc.
  pzocode: PZO9000-25E
  release_date: 2019
  short_name: Age of Ashes Player's Guide
- abbr: AoA1
  descr: Book 1 in the Age of Ashes Adventure Path.
  full_name: 'Pathfinder Adventure Path #145: Hellknight Hill'
  is_first_party: true
  isbn: 978-1-64078-173-3
  ogl_copyright_block: 'Open Game License v.1.0a (c) 2000, Wizards of the Coast, Inc.;
    System Reference Document (c) 2000, Wizards of the Coast, Inc.; Authors: Jonathan
    Tweet, Monte Cook, and Skip Williams, based on material by E. Gary Gygax and Dave
    Arneson. Pathfinder Adventure Path #145: Hellknight Hill (c) 2019, Paizo, Inc.;
    Authors: Amanda Hamon, with Logan Bonner, James Jacobs, and Jason Tondro.'
  publisher_name: Paizo, Inc.
  pzocode: PZO90145
  release_date: 2019
  short_name: Hellknight Hill
- abbr: AoA2
  descr: Book 2 in the Age of Ashes Adventure Path.
  full_name: 'Pathfinder Adventure Path #146: Cult of Cinders'
  is_first_party: true
  isbn: 978-1-64078-188-7
  ogl_copyright_block: 'Open Game License v.1.0a (c) 2000, Wizards of the Coast, Inc.;
    System Reference Document (c) 2000, Wizards of the Coast, Inc.; Authors: Jonathan
    Tweet, Monte Cook, and Skip Williams, based on material by E. Gary Gygax and Dave
    Arneson. Grippli from the Tome of Horrors Complete © 2011 Necromancer Games, Inc.,
    published and distributed by Frog God Games; Author: Scott Greene, based on original
    material by Gary Gygax. Pathfinder Adventure Path #146: Cult of Cinders (c) 2019,
    Paizo, Inc.; Authors: Eleanor Ferron, with Leo Glass, James Jacobs, Jason Keeley,
    and Owen KC Stephens.'
  publisher_name: Paizo, Inc.
  pzocode: PZO90146
  release_date: 2019
  short_name: Cult of Cinders
- abbr: AoA3
  descr: Book 3 in the Age of Ashes Adventure Path.
  full_name: 'Pathfinder Adventure Path #147: Tomorrow Must Burn'
  is_first_party: true
  isbn: 978-1-64078-191-7
  ogl_copyright_block: 'Open Game License v.1.0a (c) 2000, Wizards of the Coast, Inc.;
    System Reference Document (c) 2000, Wizards of the Coast, Inc.; Authors: Jonathan
    Tweet, Monte Cook, and Skip Williams, based on material by E. Gary Gygax and Dave
    Arneson. Pathfinder Adventure Path #147: Tomorrow Must Burn (c) 2019, Paizo, Inc.;
    Authors: Ron Lundeen and Stephanie Lundeen, with Lyz Liddell and James Sutter.'
  publisher_name: Paizo, Inc.
  pzocode: PZO90147
  release_date: 2019
  short_name: Tomorrow Must Burn
- abbr: LOWG
  descr: A gazeteer of Golarion detailing 10 diverse regions.
  full_name: Pathfinder Lost Omens World Guide (Second Edition)
  is_first_party: true
  isbn: 978-1-64078-172-6
  ogl_copyright_block: 'Open Game License v 1.0a © Wizards of the Coast, Inc.; System
    Reference Document © 2000, Wizards of the Coast, Inc.; Authors: Jonathan Tweet,
    Monte Cook, and Skip Williams, based on material by E. Gary Gygax and Dave Arneson.
    Genie, Marid from the Tome of Horrors Complete © 2011 Necromancer Games, Inc.,
    published and distributed by Frog God Games; Author: Scott Greene, based on original
    material by Gary Gygax. Pathfinder Lost Omens World Guide (Second Edition) © 2019,
    Paizo, Inc.; Authors: Tanya DePass, James Jacobs, Lyz Liddell, Ron Lundeen, Liane
    Merciel, Erik Mona, Mark Seifter, James L Sutter.'
  publisher_name: Paizo, Inc.
  pzocode: PZO9301
  release_date: 2019-08-28
  short_name: Lost Omens World Guide
